#!/bin/bash
function timering {
	local last=$(date +%s)
	last=$(($last-$tt))
	echo "Running time is $last seconds."
}
tt=$(date +%s)
trap 'timering' EXIT

style=default
debug=false
nodownload=false
path=$(dirname "${0}")
tmpdir=$(dirname $(mktemp -u))
oldtime="-10 month"
verbose=""
while [[ $# -gt 0 ]]; do
	key="$1"
	case $key in
	-a|--area)
		area=${2,,}
		shift # past argument
		shift # past value
		;;
	-s|--style)
		style=${2,,}
		shift # past argument
		shift # past value
		;;
	-d|--debug)
		debug=true
		verbose="--verbose"
		shift # past value
		;;
	-nd|--nodownload)
		nodownload=true
		shift # past argument
		shift # past value
		;;
	--help|*)
		echo -e "Usage: $0 -a name [-l name] [-d] [-nd]" >&2
		echo -e "\t-a,  --area nameofarea\tprocess area to img" >&2
		echo -e "\t-s,  --style\tProcess current style" >&2
		echo -e "\t-d,  --debug\tMore detailed statement" >&2
		echo -e "\t-nd, --nodownload\t\tDisable downloads" >&2
		echo -e "Exit status:" >&2
		echo -e "\t0     - Processed" >&2
		echo -e "\tother - Other error" >&2
		exit 1
		;;
	esac
done

function exitmsg {
	echo -e ${1}" (${2:-0})" >&2 ; exit ${2:-0}
}
function msg {
	${debug} && echo -e ${*}
}

function showFileTime {
	[ ! -e $1 ] && return 1;
	stat -L --format %Y ${1} | { read gmt ; echo `date -d "@$gmt" "+%F %T"`" "`basename ${1}`; }
}

function checkModifFile {
	[[ ! -e ${2} ]] && return 0;
	[[ ${2} -ot ${3} ]] && return 0;
	[[ ${1} -nt ${2} ]] && return 0;
	return 1;
}

function checkPrgsMkgmap {
	local prg=${1,,}
	local file="${path}/cache/${prg}-latest.zip"
	local url="https://www.mkgmap.org.uk/download/${prg}-latest.zip"
	${path}/bin/curletag ${v} --filetime "-1 day" --etagtime "-1 hour" --file ${file} ${url}
	if [ $? -eq 1 ]; then
		unzip -o -q -d "${path}/cache" ${file} || return 1
		# Create symlink
		while read line; do
			unlink "${path}/cache/${prg}" 2>/dev/null
			${debug} && echo "Create symlink ${line} ${prg}"
			ln ${v} -s -r ${line} ${path}/cache/${prg} 2>/dev/null || return 1
			break;
		done < <(ls -td ${path}/cache/${prg}-r*)
	fi;
	if [ -L ${path}/cache/${prg} ]; then
		ls -l ${path}/cache/${prg}
	else
		echo -e "${prg,^^} not found!" >&2
		return 1
	fi;
}



echo -e "\n### "`date '+%F %T'`" START"
echo -e "\n### 0. Check parameters..."

[ -z ${area} ] && errmsg 1 "The parameter area is obligatory. Use $0 --help"

msg "ROOT: ${path}"
msg "      Area: ${area} "
msg "     Style: ${style}"
msg "     Debug: ${debug}"
msg "NoDownload: ${nodownload}"


[ ! -d ${path}/area ] && mkdir -p ${path}/area
[ ! -d ${path}/cache ] && mkdir -p ${path}/cache
[ ! -d ${path}/style ] && mkdir -p ${path}/style

echo -e "\n### 0.1 Check ${area}.parameters"
[ ! -e ${path}/area/${area}.parameters ] && exitmsg "Parameters for area '${path}/area/${area}.parameters' not found!" 1;
msg ${path}/area/${area}.parameters
source ${path}/area/${area}.parameters
echo -e "FID: ${img_fid}"
echo -e "url: ${url}"

[ ! -e ${path}/area/${area}.mkgmap ] && exitmsg "Config mkgmap for area '${path}/area/${area}.mkgmap' not found!" 1;


echo -e "\n### 1. Check splitter"
checkPrgsMkgmap splitter || exit 1;

echo -e "\n### 2. Check mkgmap"
checkPrgsMkgmap mkgmap || exit 1;


if [[ ${nodownload}=false && -n "${url}" ]]; then
	msg "\n### 3. Download "`echo ${url} | awk -F[/:] '{print $4}'
`" CREATE ${srcfile}"
	${path}/bin/curletag -ft "-1 day" -f ${srcfile} ${url}
else
	[ -n "${url}" ] && msg "\n### 3. No url."
	[ ! ${nodownload} ] && msg "\n### 3. Disable download by parameter -nd."
fi;

showFileTime ${srcfile} || exitmsg "Source file ${srcfile} not found!" 1

polygonname=$(basename ${polygon})
srctmpfile_plg=$(dirname ${srcfile})"/${polygonname%.*}.${srcfile##*.}"
if [[ -n "${polygon}" && -e ${polygon} ]]; then
	if checkModifFile ${srcfile} ${srctmpfile_plg} ${polygon}; then
		echo -e "\n### 4. Create polygon from '${polygon}' to ${srctmpfile_plg}"
		osmconvert ${verbose} ${srcfile} -B=${polygon} -o=${srctmpfile_plg}
	else
		msg "\n### 4. No need to polygoned by ${polygon}"
	fi;
else
	msg "\n### 4. Polygon not exists."
	srctmpfile_plg=${srcfile}
fi;

srctmpfile_flt=cache/${polygonname}".filtered"

if [[ -n "${filter}" && -e ${filter} ]]; then
	if checkModifFile ${srctmpfile_plg} ${srctmpfile_flt} ${filter}; then
		echo -e "\n### 5. Create filter from '${filter}' to ${srctmpfile_plg}"
		echo -n "FILTERED "`date '+%F %T'` > ${srctmpfile_flt}
	else
		msg "\n### 5. No need to filtered by ${polygon}"
	fi;
else
	msg "\n###. 5 Filter not exists."
	srctmpfile_flt=${srctmpfile_plg}
fi;

srcfile=${srctmpfile_flt}
showFileTime ${srcfile} || exitmsg 1 "Source file ${srcfile} not found(2)!"
head -n 1 ${srcfile}

msg "\n### 6. Check splitter"
msg "\n### 7. Run mkgmap"

msg "\n### 8. Postprocessing"

echo -e "\n### "`date '+%F %T'`" END\n"

exit 0
####################################
filename=$(basename -- "$fullfile")
extension="${filename##*.}"
filename="${filename%.*}"
filename="${fullfile##*/}"

function check {
	local url="a"
	echo "URL '$url'"
	[ -n "${url}" ] && echo "url -n $url "
	[ -z "${url}" ] && echo "url -z $url "
	[ -e "${url}" ] && echo "url -e $url "
	[ ! -e "${url}" ] && echo "url !-e $url "
	#URL ''  url -z   url !-e
	#URL '/' url -n / url -e /
	#URL 'a' url -n a url !-e a
}


