#!/bin/bash

if [[ "$#" -ne 1 || ! -f ${1} ]]; then
	echo "Bad parameters!" >&2
	echo -e "\tUsage: $0 gpxfile" >&2
	exit 1
fi

gpx=${1}
name=$(basename -- "${gpx}")
name="${name%.*}"
echo "${name}"
echo "${name}"

while IFS= read -r line; do
#echo $line
	lat=$(echo -ne ${line} | grep -Pio '<trkpt.*lat="\K[^"]*')
	lon=$(echo -ne ${line} | grep -Pio '<trkpt.*lon="\K[^"]*')
	[[ -n ${lat} ]] && echo -e "\t${lon}    ${lat}"
done < ${gpx}
# | grep "trkpt lat"
echo "END"
echo "END"
echo "Poly ${name} created." >&2
